### ISSUE TITLE
A way to have all stations in one call

### ISSUE THREAD

**Issue by m2cci-MZL** [juliuste/oebb#24]
Hello,

Is there a way to get all stations in one call ? 

In the readme, I'll have to precise the station name, is there a way to have all the stations in one API call to store the info?

Thanks

**Comment by juliuste** [comment]
Sorry for responding after such a long time, to my best knowledge, there *generally* is no API that guarantees to contain all stations.

However, you could use the following imperfect approaches:
- [this list](https://github.com/trainline-eu/stations) contains a vast collection of stations all over Europe, but you probably won't find every bus stop in there
- you could use @derhuerst's [hafas-find-station](https://github.com/derhuerst/hafas-find-stations) (you need to replace `vbbProfile` in the example given in its readme by `const oebbProfile = require('hafas-client/p/oebb')` and adapt the bounding box to Austria).

Hope this helps in some way, please re-open if necessary 🙃
